on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: npm install
      run: npm ci
    - name: npm run build
      run: npm run build
    - name: npm run zip
      run: npm run zip
    - name: upload asset to release page
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist_zip/*.zip
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@1.1.1
      with:
        file-path: dist_zip/*.zip
        extension-id: poaolllddjlbbomnohpahbpdlcklkffi
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        glob: true
